#!/bin/sh 
#/etc/init.d/serverest
# Author: Marcelo Mariano  
# 
start() 
{ 
	java -jar TagPathAvaya.jar 
} 
stop() { 
	kill -9 `pgrep java` 2>/dev/null 
} 


case $1 in 
 start) 
   start 
 ;; 
 stop)
   stop 
 ;; 
 restart) 
   stop 
   sleep 1 
   start 
 ;; 
 *) 
 echo "Usage: $0 start|stop|restart"
 exit 1 
 ;; 
 esac 
